#!/usr/bin/env bash
set -e

pip install --no-cache-dir \
    "numpy>=1.20" \
    "pandas>=1.3" \
    "matplotlib>=3.5" \
    "seaborn>=0.11" \
    "ipywidgets>=8.0" \
    jupyter \
    nbconvert

pip install --no-cache-dir /code/
